version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: qred
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_URI}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
volumes:
  mongo:
  redis: