const STATUS_SUCCESS = 'success';
const STATUS_ERROR = 'fail';
const NUMBER_OF_EXPIRY_YEAR = 2;
const DEFAULT_PIN = '0000';

const SET_LIMIT_EXPIRATION = {
  DAILY_LIMIT: 1,
  WEEKLY_LIMIT: 7,
  MONTHLY_LIMIT: 30,
};

const MINIMUM_ACCOUNT_BALANCE = 0;

export {
  STATUS_SUCCESS,
  STATUS_ERROR,
  NUMBER_OF_EXPIRY_YEAR,
  DEFAULT_PIN,
  SET_LIMIT_EXPIRATION,
  MINIMUM_ACCOUNT_BALANCE,
};
